version: '3'
services:
  todoback:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - app-network
  todofront:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    REACT_APP_API_HOST:
      - backend
    networks:
      - app-network
  todotests:
    build: ./tests
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
    FRONT_HOST:
      - frontend
networks:
  app-network:
